global using System.Text.Json;
global using System.Net.Http.Json;
global using Simulation.Proxies;
global using Simulation.Events;
global using Simulation;
global using MQTTnet;
global using MQTTnet.Client;
global using MQTTnet.Client.Options;
global using System.Text;
